### PR TITLE
LPS-100631 Replaces legacy mixins in invitation-invite-members-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78041. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78051. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
