### PR TITLE
LPS-106792 Unifying both cases

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/83086.

**Comment by boton** [comment]
ci:test:seo

**Pull request closed without merging**
