### PR TITLE
LPS-100969 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/AliciaGarciaGarcia/liferay-portal/pull/23. [See changes here.](https://github.com/boton/liferay-portal/compare/65bffefc4281~2...65bffefc4281) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
