### PR TITLE
LPS-100630 Replaces legacy mixins in adaptive-media-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78049. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/78052. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
