### PR TITLE
LPS-104193 buildLang

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by AliciaGarciaGarcia** [comment]
ci:test:depot

**Comment by boton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/83910. [See changes here.](https://github.com/boton/liferay-portal/compare/e44da3566b2a~1...e44da3566b2a) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
