### PR TITLE
LPS-100103 Standardize Ajax requests in invite-members-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/77513. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
