### PR TITLE
LPS-110007 Organize css

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @boton, 

the YUI autosize plugin adds huge heights at the "title" and "subtitle" fields. This doesn't look good but works as expected, as the textarea increases when a long text it added in it... 
Screenshot 2020-03-17 at 13 00 11

/cc @jbalsas @marcoscv-work

### CODE REVIEW

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
This was the look & feel before the changes, check the spaces between each field 
Screenshot 2020-03-16 at 18 30 27

**Comment by boton** [comment]
Hi, @wincent 
@ambrinchaudhary have talked with @jbalsas about this and he asked to check it with you.

The [`aui-autosize-deprecated`](https://github.com/liferay/alloy-ui/blob/master-deprecated/src/aui-autosize-deprecated/js/aui-autosize-deprecated.js) plugin has a little problem: it always gives us a huge height.

We found two options to resolve this:

1. @ambrinchaudhary removed the plugin and inline @julien code in the aui:input taglib https://github.com/boton/liferay-portal/pull/150/commits/45baa3f81003b0332ac9eb74e289291d5824fd11

2. Update the `aui-autosize-deprecated` and avoid adding `\n` in the [DEFAULT_APPEND_CONTENT](https://github.com/liferay/alloy-ui/blob/master-deprecated/src/aui-autosize-deprecated/js/aui-autosize-deprecated.js#L23) or unless avoid the [concatenation](https://github.com/liferay/alloy-ui/blob/master-deprecated/src/aui-autosize-deprecated/js/aui-autosize-deprecated.js#L190) of this DEFAULT_APPEND_CONTENT

What do you think?

Thanks in advance

**Comment by jbalsas** [comment]
(in case we're voting, I love Door Number 1 😂)

**Comment by boton** [comment]
I prefer box number 1 too and it is already implemented by @ambrinchaudhary and @julien.

**Comment by boton** [comment]
Update the listener and works better (thanks @wincent) but I discover another problem on this solution only increases the height if you delete content nothing happens. We'll need a ["height monitor"](https://github.com/liferay/alloy-ui/blob/master-deprecated/src/aui-autosize-deprecated/js/aui-autosize-deprecated.js#L25) or use the plugin :(

**Comment by boton** [comment]
> Update the listener and works better (thanks @wincent) but I discover another problem on this solution only increases the height if you delete content nothing happens. We'll need a "height monitor" or use the plugin :(

@jbalsas @wincent what do you think?

**Comment by boton** [comment]
Pull request submitted to https://github.com/julien/liferay-portal/pull/238. [See changes here.](https://github.com/boton/liferay-portal/compare/1b4de338018f~1...1b4de338018f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
