### PR TITLE
LPS-106488 Inject request/response

### PR DESCRIPTION
**Pull request by adolfopa**
@boton You need to look at the list display style, which is not working properly (adjust styles and hook in Js selection logic).

When finished, send back to me. Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1241. [See changes here.](https://github.com/boton/liferay-portal/compare/be13dc956bc6~1...be13dc956bc6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/336. [See changes here.](https://github.com/boton/liferay-portal/compare/43232d4188e7~1...43232d4188e7) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
