### PR TITLE
LPS-102559 Update DocumentPreviewer component to use React

### PR DESCRIPTION
**Pull request by wincent**
I reviewed this here: https://github.com/wincent/liferay-portal/pull/77

Looks good to me.

### CODE REVIEW

**Comment by markocikos** [comment]
@wincent @boton I ninja-added a commit that sets wrapper in component file, after I've seen this this pattern in other files, for example [this one](https://github.com/liferay/liferay-portal/blob/81a7155fce2487a51e4140e19be312c4e659d044/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/ChangeDefaultLanguage.es.js#L109).

**Comment by wincent** [comment]
giphy-downsized

**Comment by jbalsas** [comment]
I ninja-forwarded this to @ambrinchaudhary -> https://github.com/ambrinchaudhary/liferay-portal/pull/261

**Comment by jbalsas** [comment]
You're all welcome!!

deal_with_it_kittie

**Pull request closed without merging**
