### PR TITLE
LPS-102824 Build language autogenerated

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by boton** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/81144. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
