### PR TITLE
LPS-110068 let membership show breadcrumb or not

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/adolfopa/liferay-portal/pull/1327. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
