### PR TITLE
LPS-102560 Update ImagePreviewer component to React

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
This was originally reviewed over here:

- https://github.com/wincent/liferay-portal/pull/82
- https://github.com/wincent/liferay-portal/pull/83
- https://github.com/wincent/liferay-portal/pull/84

Sending it over to you now for final vetting. I did code-level review on those PRs but didn't test it.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Thanks, @markocikos. Sorry about the delay I had some problems with the SCSS of this module yesterday.

It awesome have to have another component in React, but the bad news is that the initial render or `Zoom to Fit` doesn't trigger a zoom calculation, because of this the `Zoom to Fit` or `Real Size` doesn't work as a toggle.

Another point is to remove the `.btn-primary` class of .floating-bar buttons to avoid this weird styles on :active.
image

**Pull request closed without merging**
