### PR TITLE
LPS-105960 - Fixes

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/boton/liferay-portal/pull/120. [See changes here.](https://github.com/boton/liferay-portal/compare/1f172f833a3b~2...1f172f833a3b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/292. [See changes here.](https://github.com/boton/liferay-portal/compare/1f172f833a3b~2...1f172f833a3b) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
